messages:
  access-denied: '&cAccess denied!'
  calc-url: '&6A good CIDR calculator can be found at &ehttps://www.ipaddressguide.com/cidr'
  blocked: 'I am sorry, but connections from your IP address are disallowed!'
  reloaded: '&eConfiguration reloaded'
  help: '&ecidr &7[&eadd &6cidr&7] [&edel &6cidr&7] [&etest &6ip&7] [&elist&7] [&ecalc&7]'
  invalid-bits: '&6%bits% &cin &6%cidr% &cis not a valid CIDR bitdepth!'
  invalid-ip: '&6%ip% &cin &6%cidr% &cis not a valid IP! (IPv4 only)'
  cidr-add-good: '&e%ip%/%bits% &6has been blacklisted'
  cidr-add-fail: '&e%ip%/%bits% &cis already blacklisted!'
  cidr-remove-good: '&e%cidr% &6has been un-blacklisted'
  cidr-remove-fail: '&e%cidr% &cis not blacklisted'
  list-none: '&eThere are current no CIDR blocks being blacklisted'
  list-header: '&eCurrent CIDR blocks being blacklisted%br%'
  list-data: '&6%cidr%'
  test-good: '&6%ip% &amatches &6the blacklist'
  test-fail: '&6%ip% &cdoes not match &6the blacklist'